### ISSUE TITLE
svelte: stale is forever true w/ cache-and-network

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#1031]
urql version & exchanges:

```json
"@urql/exchange-graphcache": "3.1.3",
"@urql/svelte": "1.0.0",
"graphql": "15.3.0",
"graphql-tag": "2.11.0",
"svelte": "3.29.0",
```

**Steps to reproduce**

1. Start the server opening this page: https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl
1. Open Incognito browser session
1. Go to reproduction: https://jkiko.csb.app/
1. Click on "Todos list"
1. The list shows, `stale` is `false`, ok
1. Click on the first todo link "Open"
1. The todo shows, `stale` is `false`, ok
1. Refresh the page
1. The same todo shows, `stale` is `true` forever
1. Go back with browser button
1. The todo list shows, but `stale` is `true` now

**Expected behavior**

`stale` is `false` after the server response

**Actual behavior**

`stale` always remains `true` even after the server response

**Additional**

[CodeSandBox client project](https://codesandbox.io/s/urql-svelte-cache-and-network-stale-true-forever-jkiko?file=/Todo.svelte)
[CodeSandBox server project](https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl)

**Comment by kitten** [comment]
Nice catch, @frederikhors & @JoviDeCroock! 🙌

**Comment by kitten** [comment]
Fixed in new release `@urql/svelte@1.0.1` https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fsvelte%401.0.1

**Comment by frederikhors** [comment]
@JoviDeCroock @kitten

Unfortunately this issue is still **NOT** fixed.

I updated `package.json` changing from

`"@urql/svelte": "1.0.0"`

to

`"@urql/svelte": "1.0.1"` and it has the same problem.

If I use `"@urql/svelte": "https://pkg.csb.dev/FormidableLabs/urql/commit/4550be11/@urql/svelte"` **it works!**

**Comment by frederikhors** [comment]
@JoviDeCroock @kitten this is still a problem with `@urql/svelte 1.1.0`.

Can you please re-open this?

💀 **THIS IS IMPORTANT.** 💀

Thank you.

**Comment by JoviDeCroock** [comment]
Does https://github.com/FormidableLabs/urql/pull/1044 fix it?

**Comment by frederikhors** [comment]
Oh! Wow!

I lost this!

It works. I tried now.

**Comment by kitten** [comment]
Oh double wow. I forgot to merge that before the release 😂
