### ISSUE TITLE
Issue: Next js build failure (Can't import named export `Provider`)

### ISSUE THREAD

**Issue by skene** [FormidableLabs/urql#644]
Attempting to build urql with next js,i receive the following errors depending on how the app is set up:

`Can't import the named export 'concat' from non EcmaScript module (only default export is available)`

`Can't import the named export 'Provider' from non EcmaScript module (only default export is available)`

**urql version**
1.10.3

** nextjs version **
9.3.0

**Steps to reproduce**
https://github.com/skene/nextjs-with-urql

**Expected behavior**

build successfully.

**Actual behavior**
fails on build.

**Comment by JoviDeCroock** [comment]
We're actively working on fixing this, linked issue: https://github.com/FormidableLabs/urql/issues/640

**Comment by skene** [comment]
Ha oops, i just saw that issue as i submitted this one.

**Comment by JoviDeCroock** [comment]
No worries, glad you did bring it to our attention that it's not only Create-react-app struggling with Node 13

**Comment by skene** [comment]
This issue is still persisting. 

`Can't import the named export 'createContext' from non EcmaScript module (only default export is available)`

**Comment by kitten** [comment]
Okay, `urql@1.9.4` and `next-urql@0.3.6` have been fixed up to account for `react` having no ESM bundle. The fixes for #636 have created a ripple effect of us trying to utilise `.mjs` and `package.json:exports` correctly and consistently and on the way we also ran into a Webpack issue. Sorry about that! 🙏

**Comment by skene** [comment]
Awesome, thanks a lot for being so fast and communicative!

**Comment by geisterfurz007** [comment]
Hey, quick question: Is there a chance this is still occuring with the `@urql/preact` package? I have had a bunch of strange issues with package resolution in my mono-repo setup so I am not sure if urql is the cause or my project structure. The error is pretty much identical to the one reported by skene:

```
error - D:/Projects/JavaScript/fullstack-typescript-boilerplate/node_modules/@urql/preact/dist/urql-preact.mjs
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
```

If caused by the package, I would love to help out but I am quite inexperienced in juggling the different JS formats so I would probably need a pointer or two.

**Comment by kitten** [comment]
@geisterfurz007 We haven't observed this yet. It's also an odd one because Preact does have `package.json:exports` and `mjs` bundles in its release. This could be a resolution issue, but that being said, I have no idea how your project is set up and what's going on with the import resolution, so it's hard for me to tell. Feel free to pop into GH Discussions with a thread and some more information about your setup though and we'll see what we can do

**Comment by geisterfurz007** [comment]
Alright, I will try my best to reproduce this on a small scale tomorrow then and post in Discussions if I am able to do it. After a few hours of battling webpack and other tooling I was just desperately hoping I didn't mess up once more.
Thanks for the fast response, I really appreciate it!
